# WARNING: this file is not suitable for production, please use with caution
version: '2'

services:
  web:
    image: library
    build: .
    command: library run -h 0.0.0.0
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/library.db
    volumes:
      - ./library:/code/library
      - ./db/:/db/
    ports:
      - "5000:5000"
